openapi: "3.0.0"
info:
  title: API Automation Service Sitionix
  description: API specification for automation service
  version: 0.0.1
  contact:
    name: APP Sitionix
servers:
  - description: Localhost (dev only)
    url: 'http://localhost:9083/atmssox'
tags:
  - name: Agent
paths:
  /api/v1/agents:
    $ref: './paths/v1/agents.yml'
  /api/v1/agents/{agentId}:
    $ref: './paths/v1/agents-by-id.yml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Service-to-service access token (Bearer).
  schemas:
    CreateAgentRequestDTO:
      $ref: './schemas/v1/agent/create-agent-request-dto.yml#/CreateAgentRequest'
    AgentDTO:
      $ref: './schemas/v1/agent/agent-dto.yml#/Agent'
    AgentsResponseDTO:
      $ref: './schemas/v1/agent/agents-response-dto.yml#/AgentsResponse'
    ErrorDTO:
      $ref: '../../common/rest/openapi.yml#/components/schemas/ErrorDTO'
  responses:
    BadRequest:
      $ref: '../../common/rest/openapi.yml#/components/responses/BadRequest'
    NotFound:
      $ref: '../../common/rest/openapi.yml#/components/responses/NotFound'
    Conflict:
      $ref: '../../common/rest/openapi.yml#/components/responses/Conflict'
    Gone:
      $ref: '../../common/rest/openapi.yml#/components/responses/Gone'
    InternalServerError:
      $ref: '../../common/rest/openapi.yml#/components/responses/InternalServerError'
    Unauthorized:
      $ref: '../../common/rest/openapi.yml#/components/responses/Unauthorized'
    Forbidden:
      $ref: '../../common/rest/openapi.yml#/components/responses/Forbidden'
    TooManyRequests:
      $ref: '../../common/rest/openapi.yml#/components/responses/TooManyRequests'
