name: Post Delete Unused API Version

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  detect:
    uses: ./.github/workflows/detect-metadata-changes.yml

  parse-ticket:
    runs-on: ubuntu-latest
    outputs:
      ticket: ${{ steps.extract.outputs.ticket }}
    steps:
      - name: Extract ticket from PR title
        id: extract
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "Full PR title: $title"

          if [[ "$title" =~ \[([A-Z]+-[0-9]+(-[0-9]+)?)\] ]]; then
            ticket="${BASH_REMATCH[1]}"
            ticket_lower=$(echo "$ticket" | tr '[:upper:]' '[:lower:]')
            echo "ticket=${ticket_lower}-unstable" >> $GITHUB_OUTPUT
          else
            echo "❌ Failed to extract ticket"
            exit 1
          fi

  delete-unused-version:
    needs: [detect, parse-ticket]
    if: ${{ needs.detect.outputs.changed_api == 'true' }}
    uses: ./.github/workflows/delete-unstable-workflow.yml
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix_api) }}
    with:
      name: ${{ matrix.name }}
      execution: ${{ matrix.execution }}
      ticket: ${{ needs.parse-ticket.outputs.ticket }}
      issue_number: ${{ github.event.pull_request.number }}
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}

  delete-unused-event-version:
    needs: [detect, parse-ticket]
    if: ${{ needs.detect.outputs.changed_event == 'true' }}
    uses: ./.github/workflows/delete-unstable-event-workflow.yml
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix_event) }}
    with:
      event_service: ${{ matrix.event_service }}
      event_name: ${{ matrix.event_name }}
      execution: ${{ matrix.execution }}
      ticket: ${{ needs.parse-ticket.outputs.ticket }}
      issue_number: ${{ github.event.pull_request.number }}
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}

  delete-unused-frontend-contract-version:
    needs: [detect, parse-ticket]
    if: ${{ needs.detect.outputs.changed_frontend_contract == 'true' }}
    uses: ./.github/workflows/delete-unstable-frontend-contract-workflow.yml
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix_frontend_contract) }}
    with:
      name: ${{ matrix.name }}
      execution: ${{ matrix.execution }}
      ticket: ${{ needs.parse-ticket.outputs.ticket }}
      issue_number: ${{ github.event.pull_request.number }}
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}
