name: Delete Unstable Version Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: 'API name'
      execution:
        required: true
        description: 'Execution profile (e.g. server, client)'
      ticket:
        required: true
        description: 'Ticket string (e.g. sitionix)'

jobs:
  delete:
    name: Delete Unstable Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Construct artifactId from inputs
        id: build-artifact-id
        run: |
          ARTIFACT_ID="app-afesox-${{ github.event.inputs.name }}-${{ github.event.inputs.execution }}-${{ github.event.inputs.ticket }}-unstable"
          echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Run reusable action to delete package
        uses: ./.github/actions/delete-existing-package-version
        with:
          artifact_id: ${{ steps.build-artifact-id.outputs.artifact_id }}
          token: ${{ secrets.APP_AFESOX }}
