name: Maven CI for Develop

on:
  push:
    branches:
      - develop

jobs:
  detect:
    uses: ./.github/workflows/detect-metadata-changes.yml

  build-and-deploy:
    needs: detect
    if: ${{ needs.detect.outputs.changed_api == 'true' }}
    name: ${{ format('ApiFirst • {0} • {1} • v{2}', matrix.name, matrix.execution, matrix.version) }}
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix_api) }}
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      execution: ${{ matrix.execution }}
      variant: stable
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}

  build-and-deploy-event:
    needs: detect
    if: ${{ needs.detect.outputs.changed_event == 'true' }}
    name: ${{ format('{0} • {1} • {2} • v{3}', matrix.execution == 'event-producer' && 'EventProducer' || 'EventConsumer', matrix.event_service, matrix.event_name, matrix.version) }}
    strategy:
      matrix: ${{ fromJson(needs.detect.outputs.matrix_event) }}
    uses: ./.github/workflows/build-and-deploy-event.yml
    with:
      name: ${{ matrix.name }}
      version: ${{ matrix.version }}
      execution: ${{ matrix.execution }}
      event_service: ${{ matrix.event_service }}
      event_name: ${{ matrix.event_name }}
      event_tag: ${{ matrix.event_tag }}
      event_wrapper_package: ${{ matrix.event_wrapper_package }}
      variant: stable
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}
