name: Validate OpenAPI Files

on:
  pull_request:
    paths:
      - 'apis/**/rest/**/*.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          package-manager-cache: false

      - name: Install Spectral CLI
        run: npm install -g @stoplight/spectral-cli --loglevel=error

      - name: Check Spectral version
        run: spectral --version

      - name: Fetch base branch
        run: git fetch origin "${{ github.base_ref }}" --depth=1

      - name: Validate OpenAPI entrypoints
        run: |
          CHANGED_OPENAPI_FILES=$(git diff --name-only "origin/${{ github.base_ref }}...HEAD" -- 'apis/**/rest/**/*.yml' | awk -F/ '/^apis\/[^/]+\/rest\// {print $1 "/" $2 "/rest/openapi.yml"}' | sort -u)

          if [ -z "$CHANGED_OPENAPI_FILES" ]; then
            echo "No changed REST OpenAPI entrypoints found."
            exit 0
          fi

          for file in $CHANGED_OPENAPI_FILES; do
            echo "Validating $file with Spectral..."
            spectral lint "$file" --ruleset .spectral.yaml || exit 1
          done
