name: Generate Message on Comment

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/generate') }}
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.read-definition-metadata.outputs.api_name }}
      execution: ${{ steps.find-api-spec.outputs.api_spec_type }}
      ticket: ${{ steps.extract-ticket-num.outputs.ticket_num }}
      version: ${{ steps.read-definition-metadata.outputs.api_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch and checkout pull request branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          PR_BRANCH=$(gh pr view $PR_NUMBER --json headRefName -q '.headRefName')
          echo "Pull request branch: $PR_BRANCH"
          git fetch origin $PR_BRANCH
          git checkout $PR_BRANCH

      - name: Post initial comment with workflow link
        id: post-initial-comment
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            const run_id = process.env.GITHUB_RUN_ID;
            const repo = context.repo;
            const workflow_run_url = `https://github.com/${repo.owner}/${repo.repo}/actions/runs/${run_id}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `### Workflow Execution Started\n- **Job Status:** In Progress\n- **[View Workflow Run](${workflow_run_url})**`
            });

      - name: Verify GitHub Token Access
        run: |
          if [ -z "${{ secrets.APP_AFESOX }}" ]; then
            echo "ERROR: Secret APP_AFESOX is not set or not accessible."
            exit 1
          fi

      - name: Parse command and extract name
        id: parse-command
        run: |
          api_name=$(echo '${{ github.event.comment.body }}' | grep -oP '(?<=--name \")[^\"]*')
          echo "api_name=$api_name" >> $GITHUB_OUTPUT

      - name: Extract ticket number from PR title
        id: extract-ticket-num
        run: |
          pr_title="${{ github.event.issue.title }}"
          if [[ ! "$pr_title" =~ \[.*\] ]]; then
            echo "ERROR: Pull Request title must have the correct format [SITIONIX-*] description."
            exit 1
          fi
          ticket_num=$(echo "$pr_title" | grep -oP '(?<=\[)[^]]*(?=\])' | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "ticket_num=$ticket_num" >> $GITHUB_OUTPUT

      - name: Read metadata and find api-spec-type and definition-path
        id: find-api-spec
        run: |
          api_name="${{ steps.parse-command.outputs.api_name }}"
          echo "Looking for API name: $api_name"
          api_spec_type=$(yq eval ".apis[] | select(.name == \"$api_name\") | .api-spec-type" ./apis/metadata.yml)
          definition_path=$(yq eval ".apis[] | select(.name == \"$api_name\") | .definition-path" ./apis/metadata.yml)
          echo "api_spec_type=$api_spec_type" >> $GITHUB_OUTPUT
          echo "definition_path=$definition_path" >> $GITHUB_OUTPUT

      - name: Read additional metadata from definition-path
        id: read-definition-metadata
        run: |
          metadata_file="./apis/${{ steps.find-api-spec.outputs.definition_path }}/metadata.yml"
          version=$(yq eval '.api.version' $metadata_file)
          name=$(yq eval '.api.name' $metadata_file)
          echo "api_version=$version" >> $GITHUB_OUTPUT
          echo "api_name=$name" >> $GITHUB_OUTPUT

  delete-unused-version:
    needs: build
    uses: ./.github/workflows/delete-unstable-workflow.yml
    with:
      name: ${{ needs.build.outputs.name }}
      execution: ${{ needs.build.outputs.execution }}
      ticket: ${{ needs.build.outputs.ticket }}-unstable
      issue_number: ${{ github.event.issue.number }}
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}

  deploy:
    needs: [build, delete-unused-version]
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      name: ${{ needs.build.outputs.name }}
      version: ${{ needs.build.outputs.version }}
      execution: ${{ needs.build.outputs.execution }}
      variant: ${{ needs.build.outputs.ticket }}-unstable
    secrets:
      APP_AFESOX: ${{ secrets.APP_AFESOX }}
